name = "black-enthem-mobile"
main = "index.js"
compatibility_date = "2025-12-05"

[build]
command = ""

[vars]
BRAND = "BLACK ðŸ–¤ ENTHEM"
OWNER = "@BlackEnthemOwner"
TELEGRAM = "https://t.me/blackenthem_1"
FREE_LIMIT = "100"
